FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends tzdata && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install --no-cache-dir .

CMD ["uvicorn", "app.main_worker:app", "--host", "0.0.0.0", "--port", "8001"]
